# -*- coding: utf-8 -*-
"""Prédire la survie du Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnLtLzbsDYY-sEzQHu_XCPsS1N08_yTh
"""

import sys;

print(sys.version);
print(sys.version_info  )





"""pandas==3.0.6
matplotlib==3.11.2
seaborn==0.13.2
scikit-learn==1.9.1
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -r /content/bibliothheque.txt

import matplotlib.pyplot as plt # c
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.datasets import fetch_openml
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import ConfusionMatrixDisplay, classification_report
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

import sys;
print(sys.version);
print(sys.version_info);

"""Que prépare ce code ?

L'appel fetch_openml stocke les colonnes d'entrée dans X_raw.

…
Les listes de fonctionnalités séparent les variables numériques des variables catégorielles.

L'appel copy() crée X avec seulement les cinq colonnes sélectionnées.
"""

from sklearn.datasets import fetch_openml

# Charger les données brutes et convertir la cible en entiers.

"""
plus en detail
Elle a chargé le jeu de données Titanic,
converti la variable cible y en entiers et
créé les variables X_raw, X, numeric_features,
categorical_features et selected_features comme prévu.
"""
X_raw, y = fetch_openml(
    "titanic",
    version=1,
    as_frame=True,
    return_X_y=True,
)
y = y.astype(int)

numeric_features = ["age", "fare"]
categorical_features = ["embarked", "sex", "pclass"]
selected_features = numeric_features + categorical_features
X = X_raw[selected_features].copy()

"""L'appel X.head() affiche les cinq premières lignes des variables sélectionnées.

L'appel X.isna().sum() compte les valeurs manquantes dans chaque colonne sélectionnée.

L'appel X_raw.duplicated().sum() compte les lignes entièrement dupliquées dans l'ensemble de données brutes.
"""

from sklearn.datasets import fetch_openml

X_raw, y = fetch_openml(
    "titanic",
    version=1,
    as_frame=True,
    return_X_y=True,
)
y = y.astype(int)

numeric_features = ["age", "fare"]
categorical_features = ["embarked", "sex", "pclass"]
selected_features = numeric_features + categorical_features
X = X_raw[selected_features].copy()

# Auditer avant toute modification.
print("Aperçu des données :")
print(X.head())
print("\nValeurs manquantes :")
print(X.isna().sum())
print("\nDoublons complets dans le jeu brut :")
print(X_raw.duplicated().sum())



"""Nettoyer les données et visualiser les distributions

Nettoyer une copie pour l’exploration

Avec pandas, la médiane fournit une valeur centrale pour les colonnes numériques. Le mode fournit la valeur la plus fréquente pour le port d’embarquement.

La ligne data_clean = X.copy() crée la copie réservée à l’exploration.



Les colonnes age et fare utilisent leur médiane respective comme valeur de remplacement.



La colonne embarked utilise son mode comme valeur de remplacement.



La colonne survived associe chaque passager à son étiquette de survie.



Le contrôle avec isna().sum() compte les valeurs encore absentes dans chaque colonne.
"""

# Préparer une copie nettoyée uniquement pour l'exploration.


data_clean = X.copy()
data_clean["age"] = data_clean["age"].fillna(data_clean["age"].median())
data_clean["fare"] = data_clean["fare"].fillna(data_clean["fare"].median())
data_clean["embarked"] = data_clean["embarked"].fillna(
    data_clean["embarked"].mode().iloc[0]
)
data_clean["survived"] = y

print("\nValeurs manquantes après nettoyage exploratoire :")
print(data_clean.isna().sum())

"""Tracer les distributions de classe et d’âge

Le premier graphique de seaborn compare les effectifs de chaque classe selon la survie. Le second utilise Matplotlib pour afficher une distribution empilée des âges.

Comment les graphiques sont construits





Chaque appel à plt.subplots(figsize=(7, 4)) prépare une figure avec son axe.



Le countplot compte les passagers dans chaque valeur de pclass.



La couleur définie par survived sépare les deux résultats de survie.



Le histplot répartit les âges sur l’axe horizontal.



La valeur multiple="stack" empile les groupes de survie dans chaque intervalle d’âge.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualiser les classes et la distribution des âges.
fig, ax = plt.subplots(figsize=(7, 4))
sns.countplot(data=data_clean, x="pclass", hue="survived", ax=ax)
plt.show()

fig, ax = plt.subplots(figsize=(7, 4))
sns.histplot(
    data=data_clean,
    x="age",
    hue="survived",
    multiple="stack",
    ax=ax,
)
plt.show()

"""Séparer les données brutes

La séparation entraînement-test réserve une partie des données pour l’évaluation finale. Cette frontière empêche les informations du jeu de test d’influencer l’entraînement.

Que fait cette séparation ?





La fonction train_test_split() crée les ensembles d’entraînement et de test à partir de X ainsi que de y.



Le paramètre test_size=0.2 réserve 20 % des lignes pour le test.



Le paramètre random_state=0 rend la séparation reproductible.



Le paramètre stratify=y conserve la répartition des classes de survie.



La variable X reste brute. La copie data_clean ne participe pas à cette séparation.
"""

from sklearn.model_selection import train_test_split

# Séparer les données brutes avant tout prétraitement prédictif.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0,
    stratify=y,
)

from sklearn.linear_model import LogisticRegression

# Obstacle volontaire : le modèle naïf reçoit encore textes et valeurs manquantes.
try:
    naive_model = LogisticRegression()
    naive_model.fit(X_train, y_train)
except (ValueError, TypeError) as error:
    print("\nÉchec attendu du modèle naïf :", type(error).__name__)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# Construire les deux branches de prétraitement.
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ]
)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore")),
    ]
)

from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_transformer, numeric_features),
        ("categorical", categorical_transformer, categorical_features),
    ]
)

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", LogisticRegression()),
    ]
)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)


print("\nRapport de classification :")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=["Non-survie", "Survie"],
    )
)

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred,
    display_labels=["Non-survie", "Survie"],
    cmap="Blues",
)
plt.show()

fig, ax = plt.subplots(figsize=(8, 5))
sns.barplot(
    data=data_clean,
    x="pclass",
    y="survived",
    hue="sex",
    errorbar=None,
    ax=ax,
)
plt.show()